# Unconstrained Optimization: Maximum Likelihood Example

In [1]:
# Example code for 2020 Computational Economics course at UZH
# code example by: Kenneth Judd, Nathan Lazarus, Philipp Mueller

In [4]:
import numpy as np
import pandas as pd
from scipy import optimize as opt
import time

### Load Data from txt file

In [9]:
ca_houses = pd.read_csv("data_CA_houses.txt", delimiter="\t")
ca_houses.set_index("ID case", inplace=True)
ca_houses.head()   # displays the first rows of your data set to give some idea of the data structure etc.

,depvar,ic1,ic2,ic3,ic4,ic5,oc1,oc2,oc3,oc4,oc5,income,agehed,rooms,ncost1,scost1,mountn,valley
ID case,,,,,,,,,,,,,,,,,,
1,1,866.00,962.64,859.90,995.76,1135.50,199.69,151.72,553.34,505.60,237.88,70000,25,6,1,0,0,0
2,1,727.93,758.89,796.82,894.69,968.90,168.66,168.66,520.24,486.49,199.19,50000,60,5,0,1,0,0
3,1,599.48,783.05,719.86,900.11,1048.30,165.58,137.80,439.06,404.74,171.47,40000,65,2,1,0,0,0
4,4,835.17,793.06,761.25,831.04,1048.70,180.88,147.14,483.00,425.22,222.95,20000,50,4,0,1,0,0
5,4,755.59,846.29,858.86,985.64,883.05,174.91,138.90,404.41,389.52,178.49,20000,25,6,0,0,0,1

### Data Processing

In [15]:
# Slice matrix ca_houses and insert into x (R ^(900x5x2))
#   x(i, j, k)        i selects IDCASE, j selects heating solution, k IC/OC 
x = np.empty((900, 5, 2)) # initialize Array

x[:, :, 0] = ca_houses.loc[:,"ic1":"ic5"]   # installation costs for heating systems 1-5
x[:, :, 1] = ca_houses.loc[:,"oc1":"oc5"]   # operation costs for heating systems 1-5
y = ca_houses["depvar"].values  #y in R^(900)

### Log Likelihood Function 

Recall that the choice probability of consumer $n$ choosing alternative $j$ is given by
\begin{equation}
P_{nj}( x_{n} | \beta ) = \displaystyle \frac{e^{(\beta' x_{nj})}}{  \displaystyle \sum_{\ell = 1}^{J} e^{(\beta' x_{n \ell})}}.
\end{equation}

Given the choice probability $P_{nj}$, the probability that consumer $n$ chooses the alternative that (s)he was actually observed choosing can be expressed as
\begin{equation}
P_{n}(\beta \vert  \{x_n, y_{nj}\}_{n=1}^N) = \sum_{n=1}^{N} \log(P_{nj} (x_{n} | \beta)).
\end{equation}

To avoid overflow errors in the exponential function, note the reformulation to
\begin{equation}
\log(P_{nj}( x_{n} | \beta )) = \displaystyle 1 - \log\left(\sum_{\ell = 1}^{J} e^{(\beta' x_{n \ell})-\beta' x_{nj}}\right).
\end{equation}

In [17]:
def log_likelihood(beta, x, y):

    beta_n  = np.dot(x,beta)  # beta * costs of all heating solutions
    betay   = np.dot(x[np.arange(x.shape[0]),y-1,:],beta.T)  # beta * costs of chosen heating solution
    log_prob = 1-np.log(np.sum(np.exp(beta_n-np.tile(betay.reshape(-1, 1), (5))), axis=1))

    return -np.sum(log_prob) #negated for minimization

### Optimization

In [33]:
# Choose starting point: Neither installation cost or operating cost are relevant
x_0 = np.zeros(2)

methods = ["Nelder-Mead","CG","BFGS"]

for solver in methods:
    tic = time.time()
    solution = opt.minimize(log_likelihood, x_0, args = (x,y), method = solver, tol = 1e-6)
    toc = time.time()
    
    try:
        jac_evals = solution.njev
    except:
        jac_evals = "N/A"
    print(solver, " \n", "Solution: ", solution.x, "time:", round(toc-tic,3), "s,  f_evals:", solution.nfev, ", jac_evals:", jac_evals)

Nelder-Mead
 Solution:  [-0.00623167 -0.0045802 ] time: 0.023 s,  f_evals: 80 , jac_evals: N/A
CG
 Solution:  [-0.00623188 -0.00458009] time: 0.098 s,  f_evals: 304 , jac_evals: 73
BFGS
 Solution:  [-0.00623188 -0.00458009] time: 0.018 s,  f_evals: 64 , jac_evals: 16